#!/usr/bin/env bash

################################################################################
#                                                                              #
#   Author: Mike 8a                                                            #
#   Description: Small shell configs                                           #
#                                                                              #
#                                     -`                                       #
#                     ...            .o+`                                      #
#                  .+++s+   .h`.    `ooo/                                      #
#                 `+++%++  .h+++   `+oooo:                                     #
#                 +++o+++ .hhs++. `+oooooo:                                    #
#                 +s%%so%.hohhoo'  'oooooo+:                                   #
#                 `+ooohs+h+sh++`/:  ++oooo+:                                  #
#                  hh+o+hoso+h+`/++++.+++++++:                                 #
#                   `+h+++h.+ `/++++++++++++++:                                #
#                            `/+++ooooooooooooo/`                              #
#                           ./ooosssso++osssssso+`                             #
#                          .oossssso-````/osssss::`                            #
#                         -osssssso.      :ssss``to.                           #
#                        :osssssss/  Mike  osssl   +                           #
#                       /ossssssss/   8a   +sssslb                             #
#                     `/ossssso+/:-        -:/+ossss'.-                        #
#                    `+sso+:-`                 `.-/+oso:                       #
#                   `++:.                           `-/+/                      #
#                   .`   github.com/mike325/dotfiles   `/                      #
#                                                                              #
################################################################################

[[ $- == *i* ]] && __INTERACTIVE=1 || __INTERACTIVE=0


################################################################################
#                               Some vim stuff                                 #
# Use <C-s> in terminal vim                                                    #
(( __INTERACTIVE == 1 )) && stty -ixon                                         #
# Set vi keys in the shell                                                     #
set -o vi

# Make backspace delete in a sane way
stty erase '^?'
################################################################################

################################################################################
#                         Make some dir that I normally use                    #
################################################################################
[[ ! -d "$HOME/.local/bin" ]] && mkdir -p "$HOME/.local/bin"
[[ ! -d "$HOME/.local/lib" ]] && mkdir -p "$HOME/.local/lib"
[[ ! -d "$HOME/.local/share" ]] && mkdir -p "$HOME/.local/share"
[[ ! -d "$HOME/.local/golang/src" ]] && mkdir -p "$HOME/.local/golang/src"
[[ ! -d "$HOME/.local/golang/pkgs" ]] && mkdir -p "$HOME/.local/golang/pkgs"
# [[ ! -d "$HOME/.local/git/template" ]] && mkdir -p "$HOME/.local/git/template"
# [[ ! -d "$HOME/.local/git/hooks" ]] && mkdir -p "$HOME/.local/git/hooks"
# [[ ! -d "$HOME/.local/git/bin" ]] && mkdir -p "$HOME/.local/git/bin"

# Load profile settings
# if [[ -f $HOME/.profile ]]; then
#     source $HOME/.profile
# fi

# Load all proxy settings
if [[ -f "$HOME/.config/shell/host/proxy"  ]]; then
    source "$HOME/.config/shell/host/proxy"
fi

# Load all ENV variables
if [[ -f "$HOME/.config/shell/host/env"  ]]; then
    source "$HOME/.config/shell/host/env"
fi

if [[ -d "$HOME/.local/git/bin" ]]; then
    export PATH="$HOME/.local/git/bin:$PATH"
fi

if [[ -d "$HOME/.local/bin/" ]]; then
    export PATH="$HOME/.local/bin/:$PATH"
fi

# If you have a custom pythonstartup script, you could set it in "env" file
if [[ -f "$HOME/.local/lib/pythonstartup.py" ]]; then
    export PYTHONSTARTUP="$HOME/.local/lib/pythonstartup.py"
elif [[ -f "$PYTHONSTARTUP_SCRIPT" ]]; then
    export PYTHONSTARTUP="$PYTHONSTARTUP_SCRIPT"
fi

# if hash gem 2> /dev/null; then
#     _GEM_USER_PATH=$(gem environment | grep -i 'user install' | awk '{print $5}')
#     if [[ -d "${_GEM_USER_PATH}/bin" ]]; then
#         export PATH="${_GEM_USER_PATH}/bin:$PATH"
#     fi
# fi

# If Neovim is installed in a different path, you could set it in "env" file
if [[ -d "$HOME/.local/neovim/bin" ]]; then
    export PATH="$HOME/.local/neovim/bin:$PATH"
elif [[ -d "$NEOVIM_PATH" ]]; then
    export PATH="$NEOVIM_PATH:$PATH"
fi

if [[ -d "$HOME/.local/golang/bin" ]]; then
    export PATH="$HOME/.local/golang/bin:$PATH"
fi

if [[ -d "$HOME/.local/golang/src" ]]; then
    export GOPATH="$HOME/.local/golang/src"
fi

################################################################################
#                       Load the settings, alias and framework                 #
################################################################################

# We don't need this stuff if we are in a non __INTERACTIVE session

# Windows stuff
if [[ $(uname --all) =~ MINGW ]]; then
    export _CURRENT_SHELL="$(ps | grep `echo $$` | awk '{ print $8 }')"
    export _CURRENT_SHELL="${_CURRENT_SHELL##*/}"
    export _IS_WINDOWS=1
else
    export _CURRENT_SHELL="$(ps | grep `echo $$` | awk '{ print $4 }')"
fi

export _DEFAULT_SHELL="${SHELL##*/}"

if (( __INTERACTIVE == 1 )); then

    # Make less colorful
    export LESS=' -R '

    # Load custom shell framework settings (override default shell framework settings)
    if [[ -f  "$HOME/.config/shell/host/framework_settings" ]]; then
        source "$HOME/.config/shell/host/framework_settings"
    fi

    # Configure shell framework and specific shell settings (Just bash and zsh)
    # are supported
    if [[ -f  "$HOME/.config/shell/${_CURRENT_SHELL}_settings" ]]; then
        source "$HOME/.config/shell/${_CURRENT_SHELL}_settings"

        # I prefer the cool sl and the bins in my path
        _kill_alias=(ips usage myip del down4me)

        for i in "${_kill_alias[@]}"; do
            if [[ "$(command -V $i)" =~ "function" ]]; then
                unset -f "$i"
            elif [[ "$(command -V $i)" =~ "alias" ]]; then
                unalias "$i"
            fi
        done
    fi

    # Load alias after bash-it to give them higher priority
    if [[ -f "$HOME/.config/shell/alias"  ]]; then
        source "$HOME/.config/shell/alias"
    fi

    # Load host settings (override general alias and funtions)
    if [[ -f  "$HOME/.config/shell/host/settings" ]]; then
        source "$HOME/.config/shell/host/settings"
    fi

    if [[ -f "$HOME/.config/shell/banner" ]]; then
        cat "$HOME/.config/shell/banner"
    fi
fi
