#!/usr/bin/env bash

################################################################################
#                                                                              #
#   Author: Mike 8a                                                            #
#   Description: Small shell configs                                           #
#                                                                              #
#                                     -`                                       #
#                     ...            .o+`                                      #
#                  .+++s+   .h`.    `ooo/                                      #
#                 `+++%++  .h+++   `+oooo:                                     #
#                 +++o+++ .hhs++. `+oooooo:                                    #
#                 +s%%so%.hohhoo'  'oooooo+:                                   #
#                 `+ooohs+h+sh++`/:  ++oooo+:                                  #
#                  hh+o+hoso+h+`/++++.+++++++:                                 #
#                   `+h+++h.+ `/++++++++++++++:                                #
#                            `/+++ooooooooooooo/`                              #
#                           ./ooosssso++osssssso+`                             #
#                          .oossssso-````/osssss::`                            #
#                         -osssssso.      :ssss``to.                           #
#                        :osssssss/  Mike  osssl   +                           #
#                       /ossssssss/   8a   +sssslb                             #
#                     `/ossssso+/:-        -:/+ossss'.-                        #
#                    `+sso+:-`                 `.-/+oso:                       #
#                   `++:.                           `-/+/                      #
#                   .`   github.com/mike325/dotfiles   `/                      #
#                                                                              #
################################################################################

################################################################################
#                               Some vim stuff                                 #
# Use <C-s> in terminal vim                                                    #
[[ $- == *i* ]] && stty -ixon                                                  #
# Set vi keys in the shell                                                     #
set -o vi
################################################################################

################################################################################
#                         Make some dir that I normally use                    #
################################################################################
[[ ! -d "$HOME/.local/bin" ]] && mkdir -p "$HOME/.local/bin"
[[ ! -d "$HOME/.local/lib" ]] && mkdir -p "$HOME/.local/lib"
[[ ! -d "$HOME/.local/share" ]] && mkdir -p "$HOME/.local/share"
[[ ! -d "$HOME/.local/golang/src" ]] && mkdir -p "$HOME/.local/golang/src"
# [[ ! -d "$HOME/.local/git/template" ]] && mkdir -p "$HOME/.local/git/template"
# [[ ! -d "$HOME/.local/git/hooks" ]] && mkdir -p "$HOME/.local/git/hooks"
# [[ ! -d "$HOME/.local/git/bin" ]] && mkdir -p "$HOME/.local/git/bin"

if [[ -d "$HOME/.local/git/bin" ]]; then
    export PATH="$HOME/.local/git/bin:$PATH"
fi

if [[ -d $HOME/.local/bin/ ]]; then
    export PATH="$HOME/.local/bin/:$PATH"
fi

# If you have a custom pythonstartup script, you could set it in "host_settings" file
if [[ -f $HOME/.local/lib/pythonstartup.py ]]; then
    export PYTHONSTARTUP="$HOME/.local/lib/pythonstartup.py"
elif [[ -f "$PYTHONSTARTUP_SCRIPT" ]]; then
    export PYTHONSTARTUP="$PYTHONSTARTUP_SCRIPT"
fi

# If Neovim is installed in a different path, you could set it in "host_settings" file
if [[ -d $HOME/.local/neovim/bin ]]; then
    export PATH="$HOME/.local/neovim/bin:$PATH"
elif [[ -d "$NEOVIM_PATH" ]]; then
    export PATH="$NEOVIM_PATH:$PATH"
fi

if [[ -d $HOME/.local/golang/bin ]]; then
    export PATH="$HOME/.local/golang/bin:$PATH"
fi

if [[ -d $HOME/.local/golang/src ]]; then
    export GOPATH="$HOME/.local/golang/src"
fi

################################################################################
#                       Load the settings, alias and framework                 #
################################################################################

# We don't need this stuff if we are in a non interactive session
if [[ $- == *i* ]]; then
    _DEFAULT_SHELL="${SHELL##*/}"
    _CURRENT_SHELL="$(ps | grep `echo $$` | awk '{ print $4 }')"

    # Make less colorful
    export LESS=' -R '

    # Configure shell framework and specific shell settings (Just bash and zsh)
    # are supported
    if [[ -f  "$HOME/.config/shell/${_CURRENT_SHELL}_settings" ]]; then
        source "$HOME/.config/shell/${_CURRENT_SHELL}_settings"
    fi

    # I prefer the cool sl
    if [[ "$(command -v sl)" =~ "alias" ]]; then
        unalias sl
    fi

    # Load alias after bash-it to give them higher priority
    if [[ -f "$HOME/.config/shell/alias"  ]]; then
        source "$HOME/.config/shell/alias"
    fi

    # Load host settings
    if [[ -f  "$HOME/.config/shell/host/settings" ]]; then
        source "$HOME/.config/shell/host/settings"
    fi
fi
