#!/usr/bin/env tcsh

################################################################################
#                                                                              #
#  NOT TESTED!!!! Draft of a simple/basic port of my shellrc                   #
#                                                                              #
#   Author: Mike 8a                                                            #
#   Description: Small shell configs                                           #
#                                                                              #
#                                     -`                                       #
#                     ...            .o+`                                      #
#                  .+++s+   .h`.    `ooo/                                      #
#                 `+++%++  .h+++   `+oooo:                                     #
#                 +++o+++ .hhs++. `+oooooo:                                    #
#                 +s%%so%.hohhoo'  'oooooo+:                                   #
#                 `+ooohs+h+sh++`/:  ++oooo+:                                  #
#                  hh+o+hoso+h+`/++++.+++++++:                                 #
#                   `+h+++h.+ `/++++++++++++++:                                #
#                            `/+++ooooooooooooo/`                              #
#                           ./ooosssso++osssssso+`                             #
#                          .oossssso-````/osssss::`                            #
#                         -osssssso.      :ssss``to.                           #
#                        :osssssss/  Mike  osssl   +                           #
#                       /ossssssss/   8a   +sssslb                             #
#                     `/ossssso+/:-        -:/+ossss'.-                        #
#                    `+sso+:-`                 `.-/+oso:                       #
#                   `++:.                           `-/+/                      #
#                   .`   github.com/mike325/dotfiles   `/                      #
#                                                                              #
################################################################################

# Magic tcsh stuff
set addsuffix
set autolist
alias cmdcwd 'set prompt="$user@`hostname`[$cwd] " '
# set correct=cmd

################################################################################
#                         Make some dir that I normally use                    #
################################################################################
if ( ! -d "$HOME/.local/bin" ) then
    mkdir -p "$HOME/.local/bin"
endif

if ( ! -d "$HOME/.local/lib" ) then
    mkdir -p "$HOME/.local/lib"
endif

if ( ! -d "$HOME/.local/share" ) then
    mkdir -p "$HOME/.local/share"
endif

if ( ! -d "$HOME/.local/golang/src" ) then
    mkdir -p "$HOME/.local/golang/src"
endif

# Load all proxy settings
if ( -f "$HOME/.config/shell/proxy.csh" ) then
    source "$HOME/.config/shell/proxy.csh"
endif

# Load all ENV variables
if ( -f "$HOME/.config/shell/env.csh" ) then
    source "$HOME/.config/shell/env.csh"
endif

### Setting the PATH var
if ( -d "$HOME/.local/git/bin" ) then
    setenv PATH "$HOME/.local/git/bin:$PATH"
endif

if ( -d "$HOME/.local/bin/" ) then
    setenv PATH "$HOME/.local/bin/:$PATH"
endif

# If you have a custom pythonstartup script, you could set it in "env.csh" file
if ( -f $HOME/.local/lib/pythonstartup.py ) then
    setenv PYTHONSTARTUP "$HOME/.local/lib/pythonstartup.py"
else if ( -f "$PYTHONSTARTUP_SCRIPT" ) then
    setenv PYTHONSTARTUP "$PYTHONSTARTUP_SCRIPT"
endif

# If Neovim is installed in a different path, you could set it in "env" file
if ( -d $HOME/.local/neovim/bin ) then
    setenv PATH "$HOME/.local/neovim/bin:$PATH"
else if ( -d "$NEOVIM_PATH" ) then
   setenv PATH "${NEOVIM_PATH}:$PATH"
endif

if ( -d "$HOME/.local/golang/bin" ) then
    setenv PATH "$HOME/.local/golang/bin:$PATH"
endif

if ( -d "$HOME/.local/golang/src" ) then
    setenv GOPATH "$HOME/.local/golang/src"
endif

################################################################################
#                       Load the settings, alias and framework                 #
################################################################################

# if ( $INTERACTIVE == 1 ) then
#     setenv _DEFAULT_SHELL "${SHELL##*/}"
#
#     # Windows stuff unsupported
#     setenv _CURRENT_SHELL "`ps | awk '{print $4}' | tail -n 1`"
#
#     # Make less colorful
#     setenv LESS ' -R '
#
#     # Load custom shell framework settings (override default shell framework settings)
#     if ( -f  "$HOME/.config/shell/host/framework_settings" ) then
#         source "$HOME/.config/shell/host/framework_settings"
#     endif
#
#     # NOTE: can't make this crap works yet
#     #
#     # Configure shell framework and specific shell settings (Just bash and zsh)
#     # are supported
#     # if ( -f  "$HOME/.config/shell/${_CURRENT_SHELL}_settings" ) then
#     #     source "$HOME/.config/shell/${_CURRENT_SHELL}_settings"
#     #
#     #     # I prefer the cool sl and the bins in my path
#     #     set _kill_alias = ( "ips" "usage" "myip" "del" "down4me" "sl" )
#     #
#     #     foreach i ($_kill_alias)
#     #         if ( "`command -V $i`" =~ "function" ) then
#     #             unset -f "$i"
#     #         else if ( "`command -V $i`" =~ "alias" ) then
#     #             unalias "$i"
#     #         endif
#     #     end
#     # endif
#
#     # Load alias after bash-it to give them higher priority
#     if ( -f "$HOME/.config/shell/alias"  ) then
#         source "$HOME/.config/shell/alias"
#     endif
#
#     # Load host settings (override general alias and funtions)
#     if ( -f  "$HOME/.config/shell/host/settings" ) then
#         source "$HOME/.config/shell/host/settings"
#     endif
# endif
