#!/usr/bin/env bash

_example()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts=(
          "--log"
          "--nolog"
          "--nocolor"
          "-v"
          "--verbose"
          "-V"
          "--version"
          "--dry"
          "--dry-run"
          "-h"
          "--help"
    )

    if [[ ${cur} == -* ]] ; then
        COMPREPLY=( $(compgen -W "${opts[*]}" -- ${cur}) )
        return 0
    fi
}

# complete -F _repo_build repo_build
