language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

install:
    - pip install flake8 pycodestyle mccabe pyflakes

script:
    - flake8 --ignore=E501 --show-source
    - find . -iname '*.sh' ! -iname 'zsh.sh'  ! -path '*/shell/scripts/*' ! -path '*/shell/host/*' -exec shellcheck --format gcc -x -a -e 1117 "{}" \;

notifications:
    email:
        recipients:
            - mickiller.25@gmail.com
        on_success: never
        on_failure: always

