language: shell

matrix:
    allow_failures:
      - name: "Testing install script with Windows"
        os: windows
        before_install:
          - choco install python git -y
        env:
          - PATH="/c/Python37:/c/Python37/Scripts:$PATH"
          - PATH="/c/Python38:/c/Python38/Scripts:$PATH"
          - IS_WINDOWS=1
    include:
      - name: "Testing stand alone script install"
        os: linux
        sudo: true
        before_install:
          - sudo apt-get install curl git wget -y
          - wget https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
          - tar xf shellcheck-latest.linux.x86_64.tar.xz
          - chmod u+x shellcheck-latest/shellcheck
          - mkdir -p "$HOME/.local/bin/" && mv shellcheck-latest/shellcheck "$HOME/.local/bin/"
          - rm -rf shellcheck-latest*
          - bash -c "./test/lint.sh --verbose"
        before_script:
          - pushd "$HOME"
          - wget https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          - chmod +x ./install.sh
          - ./install.sh --dotfiles --verbose
          - popd
        env:
          - IS_LINUX=1
      - name: "Testing install script with Linux"
        os: linux
        sudo: true
        before_install:
          - sudo apt-get install curl git -y
          - wget https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
          - tar xf shellcheck-latest.linux.x86_64.tar.xz
          - chmod u+x shellcheck-latest/shellcheck
          - mkdir -p "$HOME/.local/bin/" && mv shellcheck-latest/shellcheck "$HOME/.local/bin/"
          - rm -rf shellcheck-latest*
        before_script:
          - bash -c "./test/lint.sh --verbose"
        env:
          - IS_LINUX=1
      - name: "Testing install script with macOS"
        os: osx
        osx_image: xcode11
        before_install:
          - brew install shellcheck
        before_script:
          - bash -c "./test/lint.sh --verbose"
        env:
          - PATH="/Users/travis/Library/Python/3.7/bin:$PATH"
          - PATH="/Users/travis/Library/Python/3.8/bin:$PATH"
          - IS_MACOS=1

script:
  - ./install.sh --verbose
  - ./install.sh --verbose --force
  - if [[ -n $IS_LINUX ]]; then sudo ./install.sh --verbose --packages --only; fi
  - if [[ -n $IS_WINDOWS ]]; then ./install.sh --verbose --packages choco --only; fi

notifications:
  email:
    recipients:
      - mickiller.25@gmail.com
    on_success: never
    on_failure: always
