language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

install:
    - pip install flake8 pycodestyle mccabe pyflakes

script:
    - bash -c "./test/basic.sh --verbose"

notifications:
    email:
        recipients:
            - mickiller.25@gmail.com
        on_success: never
        on_failure: always

