#!/usr/bin/env bash

################################################################################
#                                                                              #
#   Author: Mike 8a                                                            #
#   Description: Some useful alias                                             #
#                                                                              #
#                                     -`                                       #
#                     ...            .o+`                                      #
#                  .+++s+   .h`.    `ooo/                                      #
#                 `+++%++  .h+++   `+oooo:                                     #
#                 +++o+++ .hhs++. `+oooooo:                                    #
#                 +s%%so%.hohhoo'  'oooooo+:                                   #
#                 `+ooohs+h+sh++`/:  ++oooo+:                                  #
#                  hh+o+hoso+h+`/++++.+++++++:                                 #
#                   `+h+++h.+ `/++++++++++++++:                                #
#                            `/+++ooooooooooooo/`                              #
#                           ./ooosssso++osssssso+`                             #
#                          .oossssso-````/osssss::`                            #
#                         -osssssso.      :ssss``to.                           #
#                        :osssssss/  Mike  osssl   +                           #
#                       /ossssssss/   8a   +sssslb                             #
#                     `/ossssso+/:-        -:/+ossss'.-                        #
#                    `+sso+:-`                 `.-/+oso:                       #
#                   `++:.                           `-/+/                      #
#                   .`                                 `/                      #
#                                                                              #
################################################################################

################################################################################
#   Some usefull functions taken from https://github.com/Bash-it/bash-it/      #
################################################################################

# create a dir an move to it
function mkcd()
{
    if [[ ! -z $1 ]]; then
        mkdir "$1"
        cd "$1"
    fi
}

# disk usage per directory in Linux
function usage ()
{
    if [ -n "$1" ]; then
        du -h --max-depth=1 "$1"
    else
        du -h --max-depth=1
    fi
}

# display all ip addresses for this host
function ips ()
{
    if command -v ifconfig &>/dev/null; then
        ifconfig | awk '/inet /{ print $2 }'
    elif command -v ip &>/dev/null; then
        ip addr | grep -oP 'inet \K[\d.]+'
    else
        echo "You don't have ifconfig or ip command installed!"
    fi
}

# checks whether a website is down for you, or everybody
# $ down4me http://www.google.com
function down4me ()
{
    curl -s "http://www.downforeveryoneorjustme.com/$1" | sed '/just you/!d;s/<[^>]*>//g'
}

# displays your ip address, as seen by the Internet
function myip ()
{
    res=$(curl -s checkip.dyndns.org | grep -Eo '[0-9\.]+')
    echo -e "Your public IP is: ${echo_bold_green} $res ${echo_normal}"
}

# move files to hidden folder in tmp, that gets cleared on each reboot
function del()
{
    mkdir -p /tmp/.trash && mv "$@" /tmp/.trash;
}

################################################################################
#                          Set the default text editor                         #
################################################################################

if hash nvim 2>/dev/null; then
    export EDITOR='nvim'
    VIM_PATH="$(command -v vim)"

    # Prevent to screw the path alias
    if [[ ! $VIM_PATH =~ "alias" ]]; then
        alias vim="nvim"
        alias vi="$VIM_PATH"
        alias cdvim="cd ~/.config/nvim"
        alias cdvi="cd ~/.vim"
    fi
else
    export EDITOR='vim'
    alias cdvim="cd ~/.vim"
fi

if hash emacs 2>/dev/null; then
    function cmacs() {
        emacsclient -nw "$@"
    }

    function gmacs() {
        emacsclient -c "$@" &
    }

    function dmacs() {
        emacs --daemon &
    }

    function kmacs() {
        emacsclient -e "(kill-emacs)"
    }
fi

################################################################################
#                         Small script to install neovim                       #
################################################################################

# Small script to install neovim
# Warning ! this script delete evething in the workdirectory before install
function install_neovim()
{
    # Remove all unstaged changes
    git checkout . 2>/dev/null
    # Remove all untracked files
    git clean -xdf . 2>/dev/null
    rm -r build/

    # Checkout to the stable branch
    git checkout v0.1.7 2>/dev/null

    # Prefix the current dir
    make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$(pwd)"

    # Continue only if there isn't erros
    if [[ $? -eq 0 ]]; then
        make install
        if [[ $? -eq 0 ]]; then
            export PATH="$(pwd)/bin:$PATH"
            echo You may want to add export PATH="$(pwd)/bin:\$PATH" in the shell_alias
        fi
    fi
}

################################################################################
#                          Fix my common typos                                 #
################################################################################

alias gti="git"
alias bim="vim"
alias cim="vim"
alias im="vim"

################################################################################
#                        Alias and Functions                                   #
################################################################################

alias q="exit"

function rl()
{
    rm "$@" *.log
}

alias ports="netstat -tulpn"

alias grep="grep --color -n"
alias grepo="grep -o"
alias grepe="grep -E"

alias ls='ls --color'
alias la="ls -A"
alias ll="ls -lh"
alias lla="ls -lhA"
alias cl="clear"
alias turnoff="sudo poweroff"

# Function to go back any number of dirs
function bk()
{
    if [[ ! -z "$1" ]] && [[ $1 =~ ^[0-9]+$ ]]; then
        PARENT="./"

        for (( i = 0; i < $1; i++ )); do
            PARENT="${PARENT}../"
        done
        cd "$PARENT"
    elif [[ -z "$1" ]]; then
        cd ..
    else
        echo "Unexpected arg $1"
        return 1
    fi
}

alias salias="source ~/.shell_alias"
alias sset="source ~/.shell_settings"

######## This way sudo commands get the alias of the account
alias sudo='sudo '

######## Magnificent app which corrects your previous console command https://github.com/nvbn/thefuck
if hash thefuck 2>/dev/null; then
    eval "$(thefuck --alias)"
    alias fuck='eval $(thefuck $(fc -ln -1))'
    alias please='fuck'
fi

if hash realpath 2>/dev/null; then
    function grp()
    {
        if [[ ! -z $1 ]]; then
            realpath "$@"
        else
            realpath "."
        fi
    }
else
    function grp()
    {
        if [[ ! -z "$1" ]]; then
            cd "$1" 1> /dev/null

            if [[ $? -eq 0 ]]; then
                pwd -P
                cd - 1> /dev/null
            fi
        else
            pwd -P
        fi
    }
fi

if hash ctags 2>/dev/null; then
    alias gtf="ctags -R ."
fi

#####################    systemctl     #######################
if hash systemctl 2>/dev/null; then
    alias sysctl="sudo systemctl"
    alias usysctl="systemctl --user"

    alias ctls="sudo systemctl start"
    alias ctlk="sudo systemctl stop"
    alias ctlr="sudo systemctl restart"
    alias ctlw="sudo systemctl status"
fi

#####################    GIT     #######################
function git_stats
{
    # Awesome work from https://github.com/esc/git-stats
    # including some modifications

    if [ -n "$(git symbolic-ref HEAD 2> /dev/null)" ]; then
        echo "Number of commits per author:"
        git --no-pager shortlog -sn --all
        AUTHORS=$( git shortlog -sn --all | cut -f2 | cut -f1 -d' ')
        LOGOPTS=""
        if [[  "$1" == '-w' ]]; then
            LOGOPTS="$LOGOPTS -w"
            shift
        fi
        if [[  "$1" == '-M' ]]; then
            LOGOPTS="$LOGOPTS -M"
            shift
        fi
        if [[  "$1" == '-C' ]]; then
            LOGOPTS="$LOGOPTS -C --find-copies-harder"
            shift
        fi
        for a in $AUTHORS
        do
            echo '-------------------'
            echo "Statistics for: $a"
            echo -n "Number of files changed: "
            git log $LOGOPTS --all --numstat --format="%n" --author=$a | cut -f3 | sort -iu | wc -l
            echo -n "Number of lines added: "
            git log $LOGOPTS --all --numstat --format="%n" --author=$a | cut -f1 | awk '{s+=$1} END {print s}'
            echo -n "Number of lines deleted: "
            git log $LOGOPTS --all --numstat --format="%n" --author=$a | cut -f2 | awk '{s+=$1} END {print s}'
            echo -n "Number of merges: "
            git log $LOGOPTS --all --merges --author=$a | grep -c '^commit'
        done
    else
        echo "you're currently not in a git repository"
    fi
}

if hash git 2>/dev/null; then
    alias clone="git clone"
    alias ga="git add"
    alias gs="git status"
    alias gc="git commit"
    alias gps="git push"
    alias gpl="git pull"
    alias gco="git checkout "
    alias gr="git reset"
    alias gss="git stash save"
    alias gsp="git stash pop"
    alias gsd="git stash drop"
    alias gsa="git stash apply"
    alias gsl="git stash list"
    alias gsw="git stash show"
fi

#####################     VB      #######################
alias vbk="sudo modprobe vboxdrv"

################  package management ##################
if hash docker 2>/dev/null; then
    alias docker="sudo docker"
    alias docker-compose="sudo docker-compose"
    alias dkpa="docker ps -a"
fi

if hash yaourt 2>/dev/null; then
    alias update="yaourt -Syyu --aur"
    alias updaten="yaourt -Syyu --aur --noconfirm"
elif hash apt-get 2>/dev/null; then
    alias update="sudo apt-get update && sudo apt-get upgrade"
elif hash dnf 2>/dev/null; then
    alias update="sudo dnf update"
fi
