version: 2

root-markers:
  - .git/

commands:
  - command: notepad
    arguments:
      - ${INPUT}
    title: メモ帳

tools:
  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  # yaml-yamllint: &yaml-yamllint
  #   lint-command: 'yamllint -f parsable -'
  #   lint-stdin: true

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  lua-luacheck: &lua-luacheck
    lint-command: 'luacheck --std luajit --max-cyclomatic-complexity  15 --formatter plain %'
    lint-formats:
      - '%f:%l:%c: %m'

languages:
  vim:
    - <<: *vim-vint

  # yaml:
  #   - <<: *yaml-yamllint

  python:
    - <<: *python-flake8
    - <<: *python-black

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  lua:
    - <<: *lua-luacheck
