#!/usr/bin/env zsh

# ➤
# ▶
# $
# ❯
# »

rc="$1"
# NOTE: ignore send to background and <CTRL-c> exit codes
if [[ $rc -ne 0 ]] && [[ $rc -ne 148 ]] && [[ $rc -ne 130 ]]; then
    echo "%F{red}❯%f "
else
    echo "❯ "
fi
