#!/usr/bin/env zsh

if hash git 2>/dev/null; then
    branch="$(git branch 2>/dev/null | grep '^*' | awk '{$1=""; print $0}')"
    if [[ -n $branch ]]; then
        if [[ ${#branch} -gt 20 ]]; then
            local fer_issue_br_regex="^[ ]?[A-Za-z]+[/]([A-Za-z]+-[0-9]+-?)?"
            local issue_br_regex="^[ ]?([A-Za-z]+-[0-9]+-?)?"
            if [[ $branch =~ $fer_issue_br_regex ]]; then
                local index
                index="$(echo "$branch" | command grep -oE "$fer_issue_br_regex")"
                branch=" $(echo "$branch" | awk "{print substr(\$1,${#index})}")"
            elif [[ $branch =~ $issue_br_regex ]]; then
                local index
                index="$(echo "$branch" | command grep -oE "$issue_br_regex")"
                branch=" $(echo "$branch" | awk "{print substr(\$1,${#index})}")"
            fi
        fi
        branch="${branch/ /}"
        changes="$(git diff --shortstat 2>/dev/null | awk '{
            printf "%s~%d %s+%d %s-%d%s", "%F{yellow}", $1, "%F{green}", $4, "%F{red}", $6, "%F{blue}";
        }')"
        to_commit="$(git diff --cached --shortstat 2>/dev/null | awk '{
            printf "%s*%d", "%F{magenta}", $1;
        }')"
        stash="$(git stash list 2>/dev/null | wc -l)"
        if [[ $stash -ne 0 ]]; then
            stash=${stash##* }
            stash="%F{yellow}{$stash}"
        else
            stash=''
        fi
        info="%F{blue}|%f"
        # TODO: Find another icon to represent git branch
        if [[ -z $NO_COOL_FONTS ]]; then
            info="$info %F{white}%f"
            info="$info %F{blue}$branch%f"
        else
            info="$info %F{blue}{$branch}%f"
        fi
        [[ -n $to_commit ]] && info="$info $to_commit%f"
        [[ -n $changes ]] && info="$info $changes%f"
        [[ -n $stash ]] && info="$info $stash%f"
        info="$info %F{blue}|%f "
        echo -e "$info"
    fi
fi
