#!/usr/bin/env zsh

# TODO: May shoud cache the version and clear cache once we deactivate/change virtual env
if [[ -n $VIRTUAL_ENV ]]; then
    env_version="$(python --version | awk '{print $2}')"
    env_name="${VIRTUAL_ENV##*/}"
elif [[ -n $CONDA_DEFAULT_ENV ]]; then
    env_version="$(python --version 2>&1 | awk '{print $2}')"
    env_name="$CONDA_DEFAULT_ENV"
fi

if [[ -n $env_version ]]; then
    ENV_VERSION="${ENV_VERSION%% *}"
    echo " %F{white}(${env_name} 🐍 ${env_version})%f "
fi
