#!/usr/bin/env zsh

if hash bat 2>/dev/null ; then
    unalias -m '*-*'
    alias -g -- -h='-h 2>&1 | bat --language=help --style=plain'
    alias -g -- --help='--help 2>&1 | bat --language=help --style=plain'
    printf "$fg[gren] Alias enabled\n"
else
    printf "$fg[red][✗] Error:$fg[white]   %s\n" "Missing bat executable" 1>&2
fi
