#!/usr/bin/env zsh

function toggleProxy() {
    # shellcheck disable=SC2154
    local proxy="$HOME/.config/shell/host/proxy.sh"
    if [[ -n $http_proxy ]]; then
        unset "HTTP_PROXY"
        unset "http_proxy"
        unset "HTTPS_PROXY"
        unset "https_proxy"
        unset "ftp_proxy"
        unset "socks_proxy"
        unset "no_proxy"
        unset "NO_PROXY"
        export PROXY_DISABLE=1
        echo " ${fg[yellow]}Proxy disable"
    elif [[ -f $proxy   ]]; then
        # shellcheck disable=SC1090,SC1091
        source "$proxy"
        unset PROXY_DISABLE
        echo " ${fg[green]}Proxy enable"
    elif hash secret-tool 2>/dev/null; then
        local PROXY_PASSWORD PROXY_SERVER PROXY_PORT

        local PROXY_USER="$USER"
        local PROXY_PASSWORD="$(secret-tool lookup proxy password)"
        local PROXY_SERVER="$(secret-tool lookup proxy server)"
        local PROXY_PORT="$(secret-tool lookup proxy port)"
        if [[ -z $PROXY_SERVER ]] || [[ -z $PROXY_PASSWORD ]]; then
            echo "Cannot retrieve proxy values" 1>&2
            return 1
        fi

        local PROXY_PASSWORD=${PROXY_PASSWORD//\@/%40}
        local PROXY_PASSWORD=${PROXY_PASSWORD//\$/%24}
        local PROXY_PASSWORD=${PROXY_PASSWORD//\#/%23}
        local PROXY_PASSWORD=${PROXY_PASSWORD//\:/%3A}
        export http_proxy="http://${PROXY_USER}:${PROXY_PASSWORD}@${PROXY_SERVER}:${PROXY_PORT:-80}"
        export https_proxy="http://${PROXY_USER}:${PROXY_PASSWORD}@${PROXY_SERVER}:${PROXY_PORT:-80}"
        export ftp_proxy="http://${PROXY_USER}:${PROXY_PASSWORD}@${PROXY_SERVER}:${PROXY_PORT:-80}"
        export no_proxy="$(secret-tool lookup proxy noproxy)"
        PROXY_PASSWORD=''
        echo " ${fg[green]}Proxy enable"
    elif hash keepassxc 2>/dev/null && [[ -n $PROXY_DB ]]; then
        local cmd="keepassxc cli show -a Password "

        if [[ -n $PROXY_KEY ]]; then
            cmd="$cmd -k $PROXY_KEY"
        fi
        if [[ -n $PROXY_NOPASS ]]; then
            cmd="$cmd  --no-password"
        fi

        local proxy_cmd="$cmd -a Username -a Url $PROXY_DB"
        local proxy_variable_array=( "${(@f)$(sh -c "$proxy_cmd proxy" || error_msg "KeepassXC - Cannot find credentials for proxy!")}" )
        if [[ ${#proxy_variable_array} -eq 0 ]] || [[ -z ${proxy_variable_array[1]} ]] ; then
            echo "Cannot retrieve proxy values" 1>&2
            return 1
        fi

        local noproxy_cmd="$cmd $PROXY_DB"
        local noproxy_hosts="$(sh -c "$noproxy_cmd noproxy" || error_msg "KeepassXC - Cannot find credentials for no_proxy config!")"

        local proxy="http://${proxy_variable_array[2]}:${proxy_variable_array[1]}@${proxy_variable_array[3]}"

        export http_proxy="$proxy"
        export https_proxy="$proxy"
        export ftp_proxy="$proxy"
        export HTTPS_PROXY="$https_proxy"
        export HTTP_PROXY="$http_proxy"
        # TODO:
        if [[ -n $noproxy_hosts ]]; then
            export no_proxy="${noproxy_hosts}"
            export NO_PROXY="${NO_PROXY}"
        fi

        unset PROXY_DISABLE
        unset proxy_variable_array
        unset noproxy_hosts
        echo " ${fg[green]}Proxy enable"
    else
        echo " ${fg[red]}Missing proxy file in ${proxy}!!" 1>&2
    fi
}
