#!/usr/bin/env zsh

function toggleProxy() {
    # shellcheck disable=SC2154
    local proxy="$HOME/.config/shell/host/proxy.sh"
    if [[ -n $http_proxy ]]; then
        unset "http_proxy"
        unset "https_proxy"
        unset "ftp_proxy"
        unset "socks_proxy"
        unset "no_proxy"
        export PROXY_DISABLE=1
        echo " ${fg[yellow]}Proxy disable"
    elif [[ -f $proxy   ]]; then
        # shellcheck disable=SC1090,SC1091
        source "$proxy"
        unset PROXY_DISABLE
        echo " ${fg[green]}Proxy enable"
    else
        echo " ${fg[red]}Missing proxy file in ${proxy}!!"
    fi
}
