name: auto-format
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch install script
      run: |
        chmod +x ./install.sh
        ./install.sh --nolog --portables --verbose --force
    - name: Stylua
      run: |
        ~/.local/bin/stylua -s .
    - name: Shfmt
      run: |
        ~/.local/bin/shfmt -i 4 -s -ci -kp -w .
        ~/.local/bin/shfmt -i 4 -s -ci -kp -w ./shell/zfunctions/*
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: Autoformatter
        author_email: autoformatter@users.noreply.github.com
        message: ':art: Committing stylua and shfmt changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
