name: lint

on: [push, pull_request]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: OS Info
        run: |
          sudo apt install wget
          wget -O screenfetch-dev https://git.io/vaHfR
          chmod +x screenfetch-dev
          ./screenfetch-dev
      - name: Install dependencies
        run: |
          # Install basic packages
          sudo apt install -y curl git python3-setuptools python-setuptools
          # Setting up pip
          sudo apt install -y python3-pip
          # sudo pip3 install --upgrade pip
          # sudo pip3 install -r ./test/requirements.txt
          # Getting latest shellcheck

          GITHUB='https://github.com'
          PKG="shellcheck-latest.linux.x86_64.tar.xz"
          URL="${GITHUB}/koalaman/shellcheck"

          wget "${url}/releases/download/latest/${pkg}"
          tar xf "${pkg}"
          chmod u+x "shellcheck-latest/shellcheck"
          mkdir -p "$HOME/.local/bin/" && mv "shellcheck-latest/shellcheck" "$HOME/.local/bin/"
          rm -rf shellcheck*
      - uses: pre-commit/action@v2.0.3
