name: lint

on: [push, pull_request]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Cache precommit virutalenvs
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pre-commit/
            ~/.cache/pip/
          key: ${{runner.os}}-pre-commit-${{hashFiles('.pre-commit-config.yaml')}}
      - name: OS Info
        run: |
          sudo apt-get install wget
          wget -O screenfetch-dev https://git.io/vaHfR
          chmod +x screenfetch-dev
          ./screenfetch-dev
      - name: Install dependencies
        run: |
          # Install basic packages
          sudo apt-get install -y \
            curl               \
            git                \
            shellcheck         \
            python3-setuptools \
            python-setuptools  \
            python3-pip        \
            python3-virtualenv \
            luarocks           \
            golang

          sudo wget "https://github.com/mvdan/sh/releases/download/v3.3.1/shfmt_v3.3.1_linux_amd64" -O /usr/bin/shfmt
          sudo chmod ugo+x /usr/bin/shfmt
          mkdir -p "$HOME/.local/bin" && sudo cp /usr/bin/shfmt "$HOME/.local/bin"
      - uses: pre-commit/action@v2.0.3
