name: lint
on: [push, pull_request]

env:
  GO_VERSION: go1.18.3

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Cache precommit virutalenvs
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit/
            ~/.cache/pip/
          key: ${{runner.os}}-pre-commit-${{hashFiles('.pre-commit-config.yaml')}}
      - name: OS Info
        run: |
          sudo apt-get install wget
          wget https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch && chmod +x ./neofetch && ./neofetch
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            bison              \
            curl               \
            git                \
            shellcheck         \
            python3-setuptools \
            python3-pip        \
            python3-virtualenv \
            luarocks           \
            golang

          sudo luarocks install luacheck

          chmod +x ./install.sh
          ./install.sh --nolog --portables --verbose --force

          # FIX: Temporally fix as currently the latest tag does not have a release
          # rm -f ~/.local/bin/shfmt
          # bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
          # source "$HOME/.gvm/scripts/gvm"
          # gvm install "$GO_VERSION" -B
          # gvm use "$GO_VERSION" --default
          # go install mvdan.cc/sh/v3/cmd/shfmt@latest

          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/go/bin/" >> $GITHUB_PATH
      - name: Linting source code
        uses: pre-commit/action@v2.0.3
