name: lint
on: [push, pull_request]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Cache precommit virutalenvs
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pre-commit/
            ~/.cache/pip/
          key: ${{runner.os}}-pre-commit-${{hashFiles('.pre-commit-config.yaml')}}
      - name: OS Info
        run: |
          sudo apt-get install wget
          wget -O screenfetch-dev https://git.io/vaHfR
          chmod +x screenfetch-dev
          ./screenfetch-dev
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            bison              \
            curl               \
            git                \
            shellcheck         \
            python3-setuptools \
            python-setuptools  \
            python3-pip        \
            python3-virtualenv \
            luarocks           \
            golang

          bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
          source "$HOME/.gvm/scripts/gvm"
          gvm install go1.18.3 -B
          gvm use go1.18.3 --default
          go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - uses: pre-commit/action@v2.0.3
