name: lint

on: [push, pull_request]

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: OS Info
        run: |
          sudo apt-get install wget
          wget -O screenfetch-dev https://git.io/vaHfR
          chmod +x screenfetch-dev
          ./screenfetch-dev
      - name: Install dependencies
        run: |
          # Install basic packages
          sudo apt-get install -y \
            curl               \
            git                \
            shellcheck         \
            python3-setuptools \
            python-setuptools  \
            python3-pip        \
            python3-virtualenv \
            luarocks           \
            golang

          GO111MODULE=on sudo go get mvdan.cc/sh/v3/cmd/shfmt
      - uses: pre-commit/action@v2.0.3
